name:                pong
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/laserpants/area-51
license:             BSD3
author:              Heikki Johannes Hildén
maintainer:          hildenjohannes@gmail.com
copyright:           2022 Heikki Johannes Hildén
# category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - data-fix
  - deriving-compat
  - extra
  - llvm-hs
  - llvm-hs-pretty
  - llvm-hs-pure
  - mtl
  - recursion-schemes
  - text
  - text-show
  - transformers
  - process
  - temporary
  - newtype-generics

executables:
  pong:
    source-dirs:         src
    main:                Main.hs

tests:
  pong-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pong
    - hspec
