name:                pong
version:             0.1.0.0
homepage:            https://github.com/laserpants/area-51
license:             BSD3
author:              Heikki Johannes Hildén
maintainer:          hildenjohannes@gmail.com
copyright:           2022 Heikki Johannes Hildén
build-type:          Simple
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - data-fix
  - deriving-compat
  - extra
  - llvm-hs
  - llvm-hs-pretty
  - llvm-hs-pure
  - megaparsec
  - mtl
  - newtype-generics
  - parser-combinators
  - prettyprinter
  - process
  - recursion-schemes
  - temporary
  - text
  - text-show
  - transformers

library:
  source-dirs: 
  - src

executables:
  pong:
    main: Main.hs
    source-dirs:         
    - app

tests:
  pong-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pong
    - hspec
