name:                teriyaki
version:             0.1.0.0
homepage:            https://github.com/githubuser/teriyaki#readme
license:             BSD3
author:              Heikki Johannes Hildén
maintainer:          hildenjohannes@gmail.com
copyright:           2022 Heikki Johannes Hildén
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - data-fix
  - recursion-schemes
  - text
  - deriving-compat

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  - -Werror

executables:
  teriyaki:
    main: Main.hs
    source-dirs:
    - app
