name:                teriyaki
version:             0.1.0.0
homepage:            https://github.com/githubuser/teriyaki#readme
license:             BSD3
author:              Heikki Johannes Hildén
maintainer:          hildenjohannes@gmail.com
copyright:           2022 Heikki Johannes Hildén
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - data-fix
  - deriving-compat
  - extra
  - mtl
  - newtype-generics
  - recursion-schemes
  - set-monad
  - text
  - text-show
  - transformers

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  - -Werror

executables:
  teriyaki:
    main: Main.hs
    source-dirs:
    - app

tests:
  teriyaki-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - teriyaki
    - hspec
    - template-haskell
